name: CI Utils - Generate required secrets

on:
  workflow_dispatch:
    inputs:
      force:
        description: "Force regeneration of secrets, even when they're already present."
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      actions: write

    steps:
    - name: Check if any secrets are missing
      id: check-secrets
      run: |
        if [[ "$FORCE" == 'true' ]]; then
          echo 'Secret regeneration is forced, continuing...'
          echo 'GENERATE_SECRETS=1' >> "$GITHUB_OUTPUT"
          exit 0
        fi
        count=0

        if [[ -n "$KEYSTORE_BASE64" ]]; then
          count=$((count+1))
        fi
        if [[ -n "$STORE_PASSWORD" ]]; then
          count=$((count+1))
        fi
        if [[ -n "$KEY_ALIAS" ]]; then
          count=$((count+1))
        fi
        if [[ -n "$KEY_PASSWORD" ]]; then
          count=$((count+1))
        fi

        if (( count == 4 )); then
          echo 'All secrets are already generating, finishing...'
          echo 'GENERATE_SECRETS=0' >> "$GITHUB_OUTPUT"
          exit 0
        fi

        if (( count != 0 )); then
          echo 'Some secrets are generated, while others are not, aborting...'
          exit 1
        fi
        echo 'No secrets are present, continuing...'
        echo 'GENERATE_SECRETS=1' >> "$GITHUB_OUTPUT"
      env:
        FORCE: ${{ inputs.force }}
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      if: steps.check-secrets.outputs.GENERATE_SECRETS == '1'
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Generate key and keystore file
      run: >
        keytool
        -genkey
        -v
        -keystore diabetes-apps-key.p12
        -alias diabetes-apps-key
        -keyalg RSA
        -keysize 4096
        -validity 50000
        -keypass android
        -storepass android
        -dname 'CN=Unknown,OU=Unknown,O=Unknown,L=Unknown,ST=Unknown,C=Unknown'

    - name: Set GitHub secrets
      if: steps.check-secrets.outputs.GENERATE_SECRETS == '1'
      run: |
        gh secret set KEYSTORE_BASE64 --body "$(base64 diabetes-apps-key.p12)"
        gh secret set STORE_PASSWORD --body android
        gh secret set KEY_ALIAS --body diabetes-apps-key
        gh secret set KEY_PASSWORD --body android
      env:
        GH_REPO: ${{ github.repository }}
        GH_TOKEN: ${{ secrets.UPDATE_TOKEN || github.token }}
