# Use this command to generate a keystore if needed:
# keytool -genkey -v -keystore diabetes-apps-key.p12 -alias diabetes-apps-key -keyalg RSA -keysize 4096 -validity 50000 -keypass android -storepass android
name: Build full Android APK

on:
  workflow_dispatch:
    inputs:
      build_branch:
        description: "Branch to build from"
        required: true
        default: default
        type: choice
        options:
          - default
          - master
          - jack_patches
      perform_release:
        description: "Generate a release with built artifacts"
        required: false
        default: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      build_commit: ${{ steps.git_commit.outputs.BUILD_COMMIT }}

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.build_branch == 'default' && (vars.DEFAULT_BUILD_BRANCH || 'master') || inputs.build_branch }}

    - name: Set current git commit as job output.
      id: git_commit
      run: |
        echo "BUILD_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Create keystore file from KEYSTORE_BASE64
      run: |
        echo "$KEYSTORE_BASE64" | base64 --decode > "$HOME/keystore.p12"
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

    - name: Set swap space
      uses: pierotofy/set-swap-space@49819abfb41bd9b44fb781159c033dba90353a7c

    # https://github.com/actions/runner-images/issues/6709#issuecomment-1422895201
    # https://github.com/gradle/gradle/issues/19750
    - name: Include gradle's defaults in gradle.properties's jvmargs option
      run: |
        mkdir -p ~/.gradle
        sed -n '/^org.gradle.jvmargs=/p' gradle.properties > ~/.gradle/gradle.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: >
        ./gradlew assembleFullRelease
        "-Pandroid.injected.signing.store.file=$HOME/keystore.p12"
        "-Pandroid.injected.signing.store.password=$STORE_PASSWORD"
        "-Pandroid.injected.signing.key.alias=$KEY_ALIAS"
        "-Pandroid.injected.signing.key.password=$KEY_PASSWORD"
      env:
        STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    - name: Copy apk files from different modules to common directory
      run: |
        mkdir ~/build-output
        cp {app,wear}/build/outputs/apk/full/release/*.apk ~/build-output

    - name: Upload release artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: ~/build-output

  release:
    needs: build
    permissions:
      contents: write
    if: ${{ inputs.perform_release }}
    runs-on: ubuntu-latest
    env:
      APK_NAME: app-full-release.apk
    steps:
      - name: Download release artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-output

      - name: Get version name.
        id: version_info
        run: |
          APKANALYZER="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/apkanalyzer"
          echo "VERSION_CODE=$($APKANALYZER manifest version-code $APK_NAME)" >> $GITHUB_OUTPUT
          echo "VERSION_NAME=$($APKANALYZER manifest version-name $APK_NAME)" >> $GITHUB_OUTPUT

      - name: Update artifact names.
        env:
          VERSION_NAME: ${{ steps.version_info.outputs.VERSION_NAME }}
        run: |
          for file in *.apk; do
            mv "$file" "${file%.apk}_${VERSION_NAME}.apk"
          done

      - name: Create a release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version_info.outputs.VERSION_NAME }}
          target_commitish: ${{ needs.build.outputs.build_commit }}
          files: '*.apk'
